name: pkgcheck

on:
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pkgcore/pkgcheck-action@v1
        with:
          args: --keywords=-RedundantVersion
